In [1]:
!pip install playwright pandas
!playwright install chromium

Requirement already satisfied: playwright in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.63.0)
Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.6)
Requirement already satisfied: pyee<14,>=13 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from playwright) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from playwright) (3.4.0)
Requirement already satisfied: typing-extensions in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pyee<14,>=13->playwright) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import panads as pd

In [ ]:
# cosmetics

In [3]:
%%writefile myntra_listing.py
"""
Collect Myntra product listings (ids + urls) for many cosmetics categories into ONE csv.

Test first:
    python myntra_listing.py --cats lipstick --max-pages 2 --headed
Full run (resumable, just re-run the same command):
    python myntra_listing.py
Output: output_cosmetics/all_products_merged.csv  (product_id, url, ...)
Then:
    python myntra_variants.py --input output_cosmetics/all_products_merged.csv --follow-colours
"""
import argparse
import json
import logging
import random
import time
from pathlib import Path

import pandas as pd
from playwright.sync_api import TimeoutError as PWTimeout
from playwright.sync_api import sync_playwright

BASE = "https://www.myntra.com"
OUT = Path("output_cosmetics")
OUT.mkdir(exist_ok=True)
ROWS_F = OUT / "listing_rows.jsonl"
DONE_F = OUT / "done_pages.txt"
FINAL_CSV = OUT / "all_products_merged.csv"
DEBUG_F = OUT / "debug_listing_sample.json"

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")

CATEGORIES = [
    "lipstick", "lip-gloss", "lip-balm", "lip-liner", "foundation", "concealer",
    "primer", "compact", "blush", "highlighter", "bronzer", "setting-spray",
    "kajal", "eyeliner", "mascara", "eyeshadow", "eyebrow-pencil", "makeup-kit",
    "nail-polish", "makeup-remover", "bb-cc-cream",
    "face-wash", "face-moisturiser", "sunscreen", "face-serum", "face-mask",
    "face-scrub", "toner", "eye-cream", "body-lotion", "body-wash", "hand-cream",
    "perfume", "deodorant", "body-mist",
    "shampoo", "conditioner", "hair-oil", "hair-serum", "hair-mask", "hair-colour",
]

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("listing")


def nap(base):
    time.sleep(base + random.uniform(0, base * 0.5))


def read_listing(page, timeout=20000):
    try:
        page.wait_for_function(
            "() => window.__myx && window.__myx.searchData && window.__myx.searchData.results",
            timeout=timeout)
    except PWTimeout:
        return None
    return page.evaluate("() => window.__myx.searchData.results")


ROWS = 50


def api_page(page, cat, pg):
    """Call Myntra's own search endpoint from inside the browser session."""
    js = """
    async (a) => {
      try {
        const u = `/gateway/v2/search/${a.cat}?rows=${a.rows}&o=${a.o}&p=${a.p}&plaApplicable=false`;
        const r = await fetch(u, {credentials: 'include',
          headers: {'accept': 'application/json', 'x-meta-app': 'channel=web',
                    'x-myntraweb': 'Yes'}});
        if (!r.ok) return {__status: r.status};
        return await r.json();
      } catch (e) { return {__status: -1}; }
    }
    """
    data = page.evaluate(js, {"cat": cat, "rows": ROWS, "o": (pg - 1) * ROWS, "p": pg})
    if not isinstance(data, dict) or "__status" in data:
        log.warning("api call failed for %s page %s: %s", cat, pg,
                    data.get("__status") if isinstance(data, dict) else data)
        return None
    return data


def goto_retry(page, url, retries=3):
    for i in range(1, retries + 1):
        try:
            resp = page.goto(url, wait_until="domcontentloaded", timeout=45000)
            return resp.status if resp else 0
        except Exception as e:  # noqa: BLE001
            log.warning("goto %s/%s failed: %s", i, retries, e)
            nap(3 * i)
    return None


def parse_products(results, cat):
    rows = []
    for p in results.get("products") or []:
        pid = p.get("productId") or p.get("id")
        lp = p.get("landingPageUrl")
        if not pid or not lp:
            continue
        rows.append({
            "product_id": str(pid),
            "url": f"{BASE}/{str(lp).lstrip('/')}",
            "category": cat,
            "name": p.get("productName") or p.get("product"),
            "brand": p.get("brand"),
            "mrp": p.get("mrp"),
            "price": p.get("price"),
            "discount_pct": p.get("discount"),
            "rating": p.get("rating"),
            "rating_count": p.get("ratingCount"),
            "sizes": p.get("sizes"),
        })
    return rows


def merge():
    if not ROWS_F.exists():
        print("Nothing to merge yet.")
        return
    rows = [json.loads(l) for l in open(ROWS_F, encoding="utf-8") if l.strip()]
    df = pd.DataFrame(rows).drop_duplicates("product_id")
    df.to_csv(FINAL_CSV, index=False, encoding="utf-8-sig")
    print(f"{FINAL_CSV}: {len(df)} unique products")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cats", nargs="*", default=CATEGORIES,
                    help="category slugs, e.g. lipstick face-wash")
    ap.add_argument("--max-pages", type=int, default=50)
    ap.add_argument("--delay", type=float, default=3.0)
    ap.add_argument("--max-blocks", type=int, default=5)
    ap.add_argument("--headed", action="store_true")
    ap.add_argument("--merge", action="store_true")
    a = ap.parse_args()

    if a.merge:
        merge()
        return

    done = set(DONE_F.read_text().split()) if DONE_F.exists() else set()
    seen = set()
    if ROWS_F.exists():
        seen = {json.loads(l)["product_id"] for l in open(ROWS_F, encoding="utf-8") if l.strip()}
    blocks = 0

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            headless=not a.headed,
            args=["--disable-blink-features=AutomationControlled"])
        ctx = browser.new_context(user_agent=UA, locale="en-IN",
                                  timezone_id="Asia/Kolkata",
                                  viewport={"width": 1366, "height": 850})
        ctx.add_init_script(
            "Object.defineProperty(navigator,'webdriver',{get:()=>undefined})")
        page = ctx.new_page()
        goto_retry(page, BASE)
        nap(a.delay)

        stop = False
        for cat in a.cats:
            if stop:
                break
            if f"{cat}|END" in done:
                log.info("%s already finished, skipping", cat)
                continue
            pg = 1
            on_cat = False
            while pg <= a.max_pages:
                key = f"{cat}|{pg}"
                if key in done:
                    pg += 1
                    continue
                if not on_cat:  # open the category once so cookies/session are set
                    status = goto_retry(page, f"{BASE}/{cat}")
                    on_cat = True
                else:
                    status = 200
                results = None
                if status and status != 404:
                    results = api_page(page, cat, pg)
                    if results is None and pg == 1:  # fallback: data embedded in the page
                        results = read_listing(page)

                if status == 404 or (results is not None and not results.get("products")):
                    log.info("%s page %s: no products, category finished", cat, pg)
                    break

                if results is None:
                    blocks += 1
                    if blocks > a.max_blocks:
                        log.error("Blocked repeatedly. Progress saved. Re-run later to resume.")
                        stop = True
                        break
                    wait = min(60 * 2 ** (blocks - 1), 900)
                    log.warning("No data (block #%s). Waiting %ss", blocks, wait)
                    time.sleep(wait)
                    continue
                blocks = 0

                if not DEBUG_F.exists():
                    DEBUG_F.write_text(json.dumps(results, ensure_ascii=False, indent=1)[:200000],
                                       encoding="utf-8")

                raw = len(results.get("products") or [])
                total = results.get("totalCount")
                rows = parse_products(results, cat)
                new_rows = [r for r in rows if r["product_id"] not in seen]
                with open(ROWS_F, "a", encoding="utf-8") as f:
                    for r in new_rows:
                        r["page"] = pg
                        f.write(json.dumps(r, ensure_ascii=False) + "\n")
                        seen.add(r["product_id"])
                done.add(key)
                with open(DONE_F, "a") as f:
                    f.write(key + "\n")
                log.info("%s page %s: raw=%s parsed=%s NEW=%s (site totalCount=%s)",
                         cat, pg, raw, len(rows), len(new_rows), total)
                if not new_rows:
                    log.info("%s page %s added nothing new, category finished", cat, pg)
                    break
                pg += 1
                nap(a.delay)
            else:
                pass
            if not stop:
                done.add(f"{cat}|END")
                with open(DONE_F, "a") as f:
                    f.write(f"{cat}|END\n")
                merge()  # checkpoint after each category
        browser.close()

    merge()


if __name__ == "__main__":
    main()

Overwriting myntra_listing.py

In [27]:
!python myntra_listing.py --cats lipstick --max-pages 4 --headed

output_cosmetics\all_products_merged.csv: 200 unique products
output_cosmetics\all_products_merged.csv: 200 unique products

2026-10-09 10:44:57,288 INFO lipstick page 1: raw=50 parsed=50 NEW=50 (site totalCount=20893)
2026-10-09 10:45:05,699 INFO lipstick page 2: raw=50 parsed=50 NEW=50 (site totalCount=20893)
2026-10-09 10:45:12,751 INFO lipstick page 3: raw=50 parsed=50 NEW=50 (site totalCount=20893)
2026-10-09 10:45:19,565 INFO lipstick page 4: raw=50 parsed=50 NEW=50 (site totalCount=20892)

In [28]:
!python myntra_listing.py --max-pages 10

^C

In [30]:
from pathlib import Path
p = Path("output_cosmetics/done_pages.txt")
p.write_text("\n".join(l for l in p.read_text().split() if not l.endswith("|END")) + "\n")
print("cleared END markers")

cleared END markers

In [32]:
!python myntra_listing.py --max-pages 10 --headed

2026-10-09 10:46:19,165 WARNING goto 1/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:46:22,532 WARNING goto 2/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:46:31,541 WARNING goto 3/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:46:45,716 INFO lipstick already finished, skipping
2026-10-09 10:46:45,839 WARNING goto 1/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lip-gloss
Call log:
  - navigating to "https://www.myntra.com/lip-gloss", waiting until "domcontentloaded"

2026-10-09 10:46:49,463 WARNING goto 2/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lip-gloss
Call log:
  - navigating to "https://www.myntra.com/lip-gloss", waiting until "domcontentloaded"

2026-10-09 10:46:56,425 WARNING goto 3/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lip-gloss
Call log:
  - navigating to "https://www.myntra.com/lip-gloss", waiting until "domcontentloaded"

2026-10-09 10:47:09,760 WARNING No data (block #1). Waiting 60s
2026-10-09 10:48:09,873 WARNING api call failed for lip-gloss page 1: -1
2026-10-09 10:48:29,905 WARNING No data (block #2). Waiting 120s
2026-10-09 10:50:29,910 WARNING api call failed for lip-gloss page 1: -1
2026-10-09 10:50:49,915 WARNING No data (block #3). Waiting 240s
2026-10-09 10:54:49,975 WARNING api call failed for lip-gloss page 1: -1
2026-10-09 10:55:09,988 WARNING No data (block #4). Waiting 480s
2026-10-09 11:03:10,048 WARNING api call failed for lip-gloss page 1: -1
2026-10-09 11:03:30,069 WARNING No data (block #5). Waiting 900s
2026-10-09 11:23:47,074 WARNING api call failed for lip-gloss page 1: -1
2026-10-09 11:24:07,095 ERROR Blocked repeatedly. Progress saved. Re-run later to resume.

output_cosmetics\all_products_merged.csv: 11652 unique products

2026-10-09 10:54:59,378 WARNING goto 1/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:55:02,857 WARNING goto 2/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:55:11,670 WARNING goto 3/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/
Call log:
  - navigating to "https://www.myntra.com/", waiting until "domcontentloaded"

2026-10-09 10:55:27,638 WARNING goto 1/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lipstick
Call log:
  - navigating to "https://www.myntra.com/lipstick", waiting until "domcontentloaded"

2026-10-09 10:55:31,324 WARNING goto 2/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lipstick
Call log:
  - navigating to "https://www.myntra.com/lipstick", waiting until "domcontentloaded"

2026-10-09 10:55:40,439 WARNING goto 3/3 failed: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.myntra.com/lipstick
Call log:
  - navigating to "https://www.myntra.com/lipstick", waiting until "domcontentloaded"

2026-10-09 10:55:50,821 WARNING No data (block #1). Waiting 60s
2026-10-09 10:56:50,840 WARNING api call failed for lipstick page 5: -1
2026-10-09 10:56:50,840 WARNING No data (block #2). Waiting 120s
2026-10-09 10:58:50,875 WARNING api call failed for lipstick page 5: -1
2026-10-09 10:58:50,876 WARNING No data (block #3). Waiting 240s
2026-10-09 11:02:50,914 WARNING api call failed for lipstick page 5: -1
2026-10-09 11:02:50,915 WARNING No data (block #4). Waiting 480s
2026-10-09 11:16:07,885 WARNING api call failed for lipstick page 5: -1
2026-10-09 11:16:07,886 WARNING No data (block #5). Waiting 900s
2026-10-09 11:31:07,923 WARNING api call failed for lipstick page 5: -1
2026-10-09 11:31:07,925 ERROR Blocked repeatedly. Progress saved. Re-run later to resume.

output_cosmetics\all_products_merged.csv: 15904 unique products
output_cosmetics\all_products_merged.csv: 500 unique products
output_cosmetics\all_products_merged.csv: 1000 unique products
output_cosmetics\all_products_merged.csv: 1500 unique products
output_cosmetics\all_products_merged.csv: 2000 unique products
output_cosmetics\all_products_merged.csv: 2500 unique products
output_cosmetics\all_products_merged.csv: 3000 unique products
output_cosmetics\all_products_merged.csv: 3500 unique products
output_cosmetics\all_products_merged.csv: 3985 unique products
output_cosmetics\all_products_merged.csv: 4485 unique products
output_cosmetics\all_products_merged.csv: 4985 unique products
output_cosmetics\all_products_merged.csv: 5074 unique products
output_cosmetics\all_products_merged.csv: 5362 unique products
output_cosmetics\all_products_merged.csv: 5860 unique products
output_cosmetics\all_products_merged.csv: 6360 unique products
output_cosmetics\all_products_merged.csv: 6860 unique products
output_cosmetics\all_products_merged.csv: 7360 unique products
output_cosmetics\all_products_merged.csv: 7699 unique products
output_cosmetics\all_products_merged.csv: 8180 unique products
output_cosmetics\all_products_merged.csv: 8680 unique products
output_cosmetics\all_products_merged.csv: 9180 unique products
output_cosmetics\all_products_merged.csv: 9622 unique products
output_cosmetics\all_products_merged.csv: 10120 unique products
output_cosmetics\all_products_merged.csv: 10620 unique products
output_cosmetics\all_products_merged.csv: 10953 unique products
output_cosmetics\all_products_merged.csv: 11452 unique products
output_cosmetics\all_products_merged.csv: 11952 unique products
output_cosmetics\all_products_merged.csv: 12452 unique products
output_cosmetics\all_products_merged.csv: 12935 unique products
output_cosmetics\all_products_merged.csv: 13414 unique products
output_cosmetics\all_products_merged.csv: 13910 unique products
output_cosmetics\all_products_merged.csv: 14410 unique products
output_cosmetics\all_products_merged.csv: 14608 unique products
output_cosmetics\all_products_merged.csv: 15104 unique products
output_cosmetics\all_products_merged.csv: 15604 unique products
output_cosmetics\all_products_merged.csv: 16104 unique products
output_cosmetics\all_products_merged.csv: 16604 unique products
output_cosmetics\all_products_merged.csv: 16911 unique products
output_cosmetics\all_products_merged.csv: 17410 unique products
output_cosmetics\all_products_merged.csv: 17909 unique products
output_cosmetics\all_products_merged.csv: 18408 unique products
output_cosmetics\all_products_merged.csv: 18908 unique products
output_cosmetics\all_products_merged.csv: 18908 unique products

2026-10-09 10:58:33,944 INFO lipstick page 5: raw=50 parsed=50 NEW=50 (site totalCount=20898)
2026-10-09 10:58:41,098 INFO lipstick page 6: raw=50 parsed=50 NEW=50 (site totalCount=20898)
2026-10-09 10:58:48,622 INFO lipstick page 7: raw=50 parsed=50 NEW=50 (site totalCount=20898)
2026-10-09 10:58:55,713 INFO lipstick page 8: raw=50 parsed=50 NEW=50 (site totalCount=20897)
2026-10-09 10:59:02,817 INFO lipstick page 9: raw=50 parsed=50 NEW=50 (site totalCount=20897)
2026-10-09 10:59:09,733 INFO lipstick page 10: raw=50 parsed=50 NEW=50 (site totalCount=20897)
2026-10-09 10:59:15,773 INFO lip-gloss page 1: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:20,416 INFO lip-gloss page 2: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:24,898 INFO lip-gloss page 3: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:29,945 INFO lip-gloss page 4: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:34,792 INFO lip-gloss page 5: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:39,587 INFO lip-gloss page 6: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:45,514 INFO lip-gloss page 7: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:49,725 INFO lip-gloss page 8: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:54,413 INFO lip-gloss page 9: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 10:59:59,339 INFO lip-gloss page 10: raw=50 parsed=50 NEW=50 (site totalCount=1974)
2026-10-09 11:00:06,481 INFO lip-balm page 1: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:10,370 INFO lip-balm page 2: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:15,267 INFO lip-balm page 3: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:20,243 INFO lip-balm page 4: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:24,061 INFO lip-balm page 5: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:29,382 INFO lip-balm page 6: raw=50 parsed=50 NEW=50 (site totalCount=2090)
2026-10-09 11:00:34,183 INFO lip-balm page 7: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:38,097 INFO lip-balm page 8: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:42,917 INFO lip-balm page 9: raw=50 parsed=50 NEW=50 (site totalCount=2090)
2026-10-09 11:00:47,645 INFO lip-balm page 10: raw=50 parsed=50 NEW=50 (site totalCount=2091)
2026-10-09 11:00:54,521 INFO lip-liner page 1: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:00,637 INFO lip-liner page 2: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:05,641 INFO lip-liner page 3: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:10,186 INFO lip-liner page 4: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:14,554 INFO lip-liner page 5: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:19,747 INFO lip-liner page 6: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:24,407 INFO lip-liner page 7: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:28,970 INFO lip-liner page 8: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:33,378 INFO lip-liner page 9: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:37,517 INFO lip-liner page 10: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:01:43,911 INFO foundation page 1: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:01:48,002 INFO foundation page 2: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:01:53,422 INFO foundation page 3: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:01:57,979 INFO foundation page 4: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:03,630 INFO foundation page 5: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:08,556 INFO foundation page 6: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:13,818 INFO foundation page 7: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:18,631 INFO foundation page 8: raw=50 parsed=50 NEW=50 (site totalCount=7818)
2026-10-09 11:02:23,680 INFO foundation page 9: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:27,877 INFO foundation page 10: raw=50 parsed=50 NEW=50 (site totalCount=7817)
2026-10-09 11:02:35,379 INFO concealer page 1: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:02:39,618 INFO concealer page 2: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:02:44,303 INFO concealer page 3: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:02:49,212 INFO concealer page 4: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:02:53,863 INFO concealer page 5: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:02:57,827 INFO concealer page 6: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:03:01,614 INFO concealer page 7: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:03:07,244 INFO concealer page 8: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:03:11,253 INFO concealer page 9: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:03:15,577 INFO concealer page 10: raw=50 parsed=50 NEW=50 (site totalCount=1744)
2026-10-09 11:03:21,007 INFO primer page 1: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:26,216 INFO primer page 2: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:30,719 INFO primer page 3: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:35,498 INFO primer page 4: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:40,017 INFO primer page 5: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:44,138 INFO primer page 6: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:49,751 INFO primer page 7: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:53,434 INFO primer page 8: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:03:58,405 INFO primer page 9: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:04:03,068 INFO primer page 10: raw=50 parsed=50 NEW=50 (site totalCount=515)
2026-10-09 11:04:08,697 INFO compact page 1: raw=50 parsed=50 NEW=41 (site totalCount=1440)
2026-10-09 11:04:12,516 INFO compact page 2: raw=50 parsed=50 NEW=48 (site totalCount=1440)
2026-10-09 11:04:16,975 INFO compact page 3: raw=50 parsed=50 NEW=49 (site totalCount=1440)
2026-10-09 11:04:21,954 INFO compact page 4: raw=50 parsed=50 NEW=47 (site totalCount=1440)
2026-10-09 11:04:26,016 INFO compact page 5: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:31,134 INFO compact page 6: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:36,038 INFO compact page 7: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:40,957 INFO compact page 8: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:45,568 INFO compact page 9: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:49,944 INFO compact page 10: raw=50 parsed=50 NEW=50 (site totalCount=1440)
2026-10-09 11:04:55,605 INFO blush page 1: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:00,376 INFO blush page 2: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:05,462 INFO blush page 3: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:09,872 INFO blush page 4: raw=50 parsed=50 NEW=50 (site totalCount=1441)
2026-10-09 11:05:14,092 INFO blush page 5: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:18,241 INFO blush page 6: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:22,600 INFO blush page 7: raw=50 parsed=50 NEW=50 (site totalCount=1441)
2026-10-09 11:05:26,774 INFO blush page 8: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:31,069 INFO blush page 9: raw=50 parsed=50 NEW=50 (site totalCount=1442)
2026-10-09 11:05:37,053 INFO blush page 10: raw=50 parsed=50 NEW=50 (site totalCount=1441)
2026-10-09 11:05:43,661 INFO highlighter page 1: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:05:49,024 INFO highlighter page 2: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:05:54,634 INFO highlighter page 3: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:05:58,864 INFO highlighter page 4: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:03,799 INFO highlighter page 5: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:08,639 INFO highlighter page 6: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:13,866 INFO highlighter page 7: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:18,287 INFO highlighter page 8: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:22,882 INFO highlighter page 9: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:27,853 INFO highlighter page 10: raw=50 parsed=50 NEW=50 (site totalCount=1126)
2026-10-09 11:06:33,884 INFO bronzer page 1: raw=50 parsed=50 NEW=50 (site totalCount=89)
2026-10-09 11:06:38,158 INFO bronzer page 2: raw=39 parsed=39 NEW=39 (site totalCount=89)
2026-10-09 11:06:42,323 INFO bronzer page 3: no products, category finished
2026-10-09 11:06:44,527 INFO setting-spray page 1: raw=50 parsed=50 NEW=49 (site totalCount=289)
2026-10-09 11:06:49,073 INFO setting-spray page 2: raw=50 parsed=50 NEW=50 (site totalCount=289)
2026-10-09 11:06:53,068 INFO setting-spray page 3: raw=50 parsed=50 NEW=50 (site totalCount=289)
2026-10-09 11:06:58,336 INFO setting-spray page 4: raw=50 parsed=50 NEW=50 (site totalCount=289)
2026-10-09 11:07:02,483 INFO setting-spray page 5: raw=50 parsed=50 NEW=50 (site totalCount=289)
2026-10-09 11:07:06,456 INFO setting-spray page 6: raw=39 parsed=39 NEW=39 (site totalCount=289)
2026-10-09 11:07:10,183 INFO setting-spray page 7: no products, category finished
2026-10-09 11:07:13,141 INFO kajal page 1: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:17,062 INFO kajal page 2: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:22,281 INFO kajal page 3: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:27,602 INFO kajal page 4: raw=50 parsed=50 NEW=49 (site totalCount=908)
2026-10-09 11:07:31,814 INFO kajal page 5: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:36,664 INFO kajal page 6: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:41,524 INFO kajal page 7: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:45,898 INFO kajal page 8: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:07:50,712 INFO kajal page 9: raw=50 parsed=50 NEW=49 (site totalCount=908)
2026-10-09 11:07:55,061 INFO kajal page 10: raw=50 parsed=50 NEW=50 (site totalCount=908)
2026-10-09 11:08:01,178 INFO eyeliner page 1: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:05,113 INFO eyeliner page 2: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:10,315 INFO eyeliner page 3: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:14,604 INFO eyeliner page 4: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:20,259 INFO eyeliner page 5: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:24,571 INFO eyeliner page 6: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:30,239 INFO eyeliner page 7: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:35,195 INFO eyeliner page 8: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:40,780 INFO eyeliner page 9: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:44,901 INFO eyeliner page 10: raw=50 parsed=50 NEW=50 (site totalCount=2569)
2026-10-09 11:08:51,420 INFO mascara page 1: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:08:56,189 INFO mascara page 2: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:00,265 INFO mascara page 3: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:04,090 INFO mascara page 4: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:08,428 INFO mascara page 5: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:13,990 INFO mascara page 6: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:18,057 INFO mascara page 7: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:23,168 INFO mascara page 8: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:09:27,537 WARNING api call failed for mascara page 9: -1
2026-10-09 11:09:27,538 WARNING No data (block #1). Waiting 60s
2026-10-09 11:15:46,682 INFO mascara page 9: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:15:50,451 INFO mascara page 10: raw=50 parsed=50 NEW=50 (site totalCount=732)
2026-10-09 11:15:57,074 INFO eyeshadow page 1: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:02,506 INFO eyeshadow page 2: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:06,783 INFO eyeshadow page 3: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:11,881 INFO eyeshadow page 4: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:15,887 INFO eyeshadow page 5: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:20,853 INFO eyeshadow page 6: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:26,441 INFO eyeshadow page 7: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:31,828 INFO eyeshadow page 8: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:36,181 INFO eyeshadow page 9: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:41,239 INFO eyeshadow page 10: raw=50 parsed=50 NEW=50 (site totalCount=2434)
2026-10-09 11:16:46,924 INFO eyebrow-pencil page 1: raw=50 parsed=50 NEW=49 (site totalCount=342)
2026-10-09 11:16:50,902 INFO eyebrow-pencil page 2: raw=50 parsed=50 NEW=48 (site totalCount=342)
2026-10-09 11:16:56,127 INFO eyebrow-pencil page 3: raw=50 parsed=50 NEW=50 (site totalCount=342)
2026-10-09 11:17:00,643 INFO eyebrow-pencil page 4: raw=50 parsed=50 NEW=50 (site totalCount=342)
2026-10-09 11:17:04,820 INFO eyebrow-pencil page 5: raw=50 parsed=50 NEW=50 (site totalCount=342)
2026-10-09 11:17:08,870 INFO eyebrow-pencil page 6: raw=50 parsed=50 NEW=50 (site totalCount=342)
2026-10-09 11:17:13,490 INFO eyebrow-pencil page 7: raw=42 parsed=42 NEW=42 (site totalCount=342)
2026-10-09 11:17:18,080 INFO eyebrow-pencil page 8: no products, category finished
2026-10-09 11:17:21,529 INFO makeup-kit page 1: raw=50 parsed=50 NEW=46 (site totalCount=4135)
2026-10-09 11:17:25,329 INFO makeup-kit page 2: raw=50 parsed=50 NEW=41 (site totalCount=4135)
2026-10-09 11:17:29,305 INFO makeup-kit page 3: raw=50 parsed=50 NEW=44 (site totalCount=4135)
2026-10-09 11:17:34,074 INFO makeup-kit page 4: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:37,990 INFO makeup-kit page 5: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:41,900 INFO makeup-kit page 6: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:46,185 INFO makeup-kit page 7: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:50,091 INFO makeup-kit page 8: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:55,136 INFO makeup-kit page 9: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:17:59,637 INFO makeup-kit page 10: raw=50 parsed=50 NEW=50 (site totalCount=4135)
2026-10-09 11:18:07,247 INFO nail-polish page 1: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:13,197 INFO nail-polish page 2: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:19,250 INFO nail-polish page 3: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:25,500 INFO nail-polish page 4: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:31,945 INFO nail-polish page 5: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:38,094 INFO nail-polish page 6: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:44,184 INFO nail-polish page 7: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:51,184 INFO nail-polish page 8: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:18:57,502 INFO nail-polish page 9: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:19:04,316 INFO nail-polish page 10: raw=50 parsed=50 NEW=50 (site totalCount=16514)
2026-10-09 11:19:09,461 INFO makeup-remover page 1: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:13,166 INFO makeup-remover page 2: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:17,472 INFO makeup-remover page 3: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:21,250 INFO makeup-remover page 4: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:25,943 INFO makeup-remover page 5: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:30,561 INFO makeup-remover page 6: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:35,566 INFO makeup-remover page 7: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:40,146 INFO makeup-remover page 8: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:45,068 INFO makeup-remover page 9: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:48,861 INFO makeup-remover page 10: raw=50 parsed=50 NEW=50 (site totalCount=570)
2026-10-09 11:19:54,673 INFO bb-cc-cream page 1: raw=50 parsed=50 NEW=49 (site totalCount=443)
2026-10-09 11:19:58,528 INFO bb-cc-cream page 2: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:02,631 INFO bb-cc-cream page 3: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:07,611 INFO bb-cc-cream page 4: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:12,690 INFO bb-cc-cream page 5: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:16,776 INFO bb-cc-cream page 6: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:21,200 INFO bb-cc-cream page 7: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:25,142 INFO bb-cc-cream page 8: raw=50 parsed=50 NEW=50 (site totalCount=443)
2026-10-09 11:20:29,203 INFO bb-cc-cream page 9: raw=43 parsed=43 NEW=43 (site totalCount=443)
2026-10-09 11:20:33,239 INFO bb-cc-cream page 10: no products, category finished
2026-10-09 11:20:35,621 INFO face-wash page 1: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:20:41,817 INFO face-wash page 2: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:20:46,598 INFO face-wash page 3: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:20:51,478 INFO face-wash page 4: raw=50 parsed=50 NEW=49 (site totalCount=9261)
2026-10-09 11:20:55,441 INFO face-wash page 5: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:21:00,744 INFO face-wash page 6: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:21:05,387 INFO face-wash page 7: raw=50 parsed=50 NEW=50 (site totalCount=9257)
2026-10-09 11:21:09,864 INFO face-wash page 8: raw=50 parsed=50 NEW=49 (site totalCount=9261)
2026-10-09 11:21:15,217 INFO face-wash page 9: raw=50 parsed=50 NEW=50 (site totalCount=9258)
2026-10-09 11:21:20,259 INFO face-wash page 10: raw=50 parsed=50 NEW=50 (site totalCount=9258)
2026-10-09 11:21:27,616 INFO face-moisturiser page 1: raw=50 parsed=50 NEW=50 (site totalCount=4125)
2026-10-09 11:21:33,459 INFO face-moisturiser page 2: raw=50 parsed=50 NEW=50 (site totalCount=4125)
2026-10-09 11:21:38,657 INFO face-moisturiser page 3: raw=50 parsed=50 NEW=50 (site totalCount=4125)
2026-10-09 11:21:42,857 INFO face-moisturiser page 4: raw=50 parsed=50 NEW=50 (site totalCount=4124)
2026-10-09 11:21:47,906 INFO face-moisturiser page 5: raw=50 parsed=50 NEW=50 (site totalCount=4124)
2026-10-09 11:21:52,109 INFO face-moisturiser page 6: raw=50 parsed=50 NEW=50 (site totalCount=4124)
2026-10-09 11:21:56,910 INFO face-moisturiser page 7: raw=50 parsed=50 NEW=50 (site totalCount=4124)

In [1]:
import pandas as pd
df = pd.read_csv("output_cosmetics/all_products_merged.csv")
print(len(df), "products")
print(df["category"].value_counts())

FileNotFoundError: [Errno 2] No such file or directory: 'output_cosmetics/all_products_merged.csv'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:/Users/ELCOT/OneDrive/Desktop/Data Analysis/Projects/myntra/myntra_cosmetics.csv")

In [4]:
# DATA UNDERSTANDING

In [5]:
df.head()

,product_id,url,category,name,brand,mrp,price,discount_pct,rating,rating_count,sizes,page
0,27916434,https://www.myntra.com/Lipstick/ETUDE/ETUDE-De...,lipstick,ETUDE Dear Darling Water Tint 9g - Red Grapefr...,ETUDE,450.0,382,68,4.498999,45449,8-10 ML,1
1,13105570,https://www.myntra.com/Lipstick/Lakme/Lakme-9t...,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.329039,339516,3.5-4 ML,1
2,13105598,https://www.myntra.com/Lipstick/Lakme/Lakme-9t...,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.329039,339516,3.5-4 ML,1
3,13105594,https://www.myntra.com/Lipstick/Lakme/Lakme-9t...,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.329039,339516,3.5-4 ML,1
4,30593165,https://www.myntra.com/Lipstick/Pilgrim/Pilgri...,lipstick,Pilgrim Matte Bullet Intense Colour Transferpr...,Pilgrim,595.0,357,238,4.330718,19624,4-5 ML,1

In [6]:
df.shape

(18908, 12)

In [7]:
df.size

226896

In [8]:
df.columns

Index(['product_id', 'url', 'category', 'name', 'brand', 'mrp', 'price',
       'discount_pct', 'rating', 'rating_count', 'sizes', 'page'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18908 entries, 0 to 18907
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    18908 non-null  int64
 1   url           18908 non-null  str
 2   category      18908 non-null  str
 3   name          18908 non-null  str
 4   brand         18908 non-null  str
 5   mrp           18908 non-null  float64
 6   price         18908 non-null  int64
 7   discount_pct  18908 non-null  int64
 8   rating        18908 non-null  float64
 9   rating_count  18908 non-null  int64
 10  sizes         18907 non-null  str
 11  page          18908 non-null  int64
dtypes: float64(2), int64(5), str(5)
memory usage: 5.6 MB

In [10]:
df.describe()

,product_id,mrp,price,discount_pct,rating,rating_count,page
count,1.890800e+04,18908.000000,18908.000000,18908.00000,18908.000000,18908.000000,18908.000000
mean,3.114926e+07,719.669671,472.748784,246.92088,3.354560,5175.726571,5.405120
std,1.021907e+07,749.553209,541.273897,405.20328,1.877756,23947.345949,2.870163
min,5.511300e+04,29.000000,29.000000,0.00000,0.000000,0.000000,1.000000
25%,2.451710e+07,349.000000,244.000000,50.00000,3.530612,6.000000,3.000000
50%,3.263871e+07,499.000000,349.000000,120.00000,4.357143,78.000000,5.000000
75%,3.930288e+07,799.000000,499.000000,271.00000,4.512434,821.000000,8.000000
max,4.685159e+07,18999.000000,10591.000000,8408.00000,5.000000,339516.000000,10.000000

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

product_id      0
url             0
category        0
name            0
brand           0
mrp             0
price           0
discount_pct    0
rating          0
rating_count    0
sizes           1
page            0
dtype: int64

In [13]:
df.dtypes

product_id        int64
url                 str
category            str
name                str
brand               str
mrp             float64
price             int64
discount_pct      int64
rating          float64
rating_count      int64
sizes               str
page              int64
dtype: object

In [14]:
df['product_id'].nunique()

18908

In [15]:
df['category'].unique()

<ArrowStringArray>
[        'lipstick',        'lip-gloss',         'lip-balm',
        'lip-liner',       'foundation',        'concealer',
           'primer',          'compact',            'blush',
      'highlighter',          'bronzer',    'setting-spray',
            'kajal',         'eyeliner',          'mascara',
        'eyeshadow',   'eyebrow-pencil',       'makeup-kit',
      'nail-polish',   'makeup-remover',      'bb-cc-cream',
        'face-wash', 'face-moisturiser',        'sunscreen',
       'face-serum',        'face-mask',       'face-scrub',
            'toner',        'eye-cream',      'body-lotion',
        'body-wash',       'hand-cream',          'perfume',
        'deodorant',        'body-mist',          'shampoo',
      'conditioner',         'hair-oil',       'hair-serum',
        'hair-mask',      'hair-colour']
Length: 41, dtype: str

In [16]:
df['brand'].nunique()

1701

In [17]:
df['sizes'].nunique()

469

In [18]:
# DATA CLEANING AND TRANSFPRMATION

In [19]:
# droping the null rows

df = df.dropna()

In [20]:


df.isnull().sum()

product_id      0
url             0
category        0
name            0
brand           0
mrp             0
price           0
discount_pct    0
rating          0
rating_count    0
sizes           0
page            0
dtype: int64

In [21]:
# droping unwanted columns

df = df.drop(columns = ['url','page'])

In [22]:
df.columns

Index(['product_id', 'category', 'name', 'brand', 'mrp', 'price',
       'discount_pct', 'rating', 'rating_count', 'sizes'],
      dtype='str')

In [23]:
# changing dtype

df['product_id'] = df['product_id'].astype(str)

In [24]:
# rounding the rating with only one decimal place 

df['rating'] = df['rating'].round(1)

In [25]:
df['rating'].head()

0    4.5
1    4.3
2    4.3
3    4.3
4    4.3
Name: rating, dtype: float64

In [26]:
#renaming columns

df.rename(columns = {'discount_pct':'discount_price'},inplace = True)

In [27]:
df.rename(columns = {'sizes':'volumes_ml'},inplace = True)

In [28]:
# driving discount percentage from price and  mrp

df['discount_pct'] = ((df['mrp'] - df['price'])/df['mrp']) * 100

In [29]:
df['discount_pct'] = df['discount_pct'].round(1)

In [30]:
# analysing to create discount level
df['discount_pct'].min()

np.float64(0.0)

In [31]:
df['discount_pct'].max()

np.float64(90.0)

In [32]:
# to create discount_level

df['discount_level'] = pd.cut(df['discount_pct'],
                              bins=[-1, 0, 25, 50, 75, 100],
                              labels=['no_rating', 'low', 'medium', 'high', 'very_high'])

In [33]:
df.head()

,product_id,category,name,brand,mrp,price,discount_price,rating,rating_count,volumes_ml,discount_pct,discount_level
0,27916434,lipstick,ETUDE Dear Darling Water Tint 9g - Red Grapefr...,ETUDE,450.0,382,68,4.5,45449,8-10 ML,15.1,low
1,13105570,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.3,339516,3.5-4 ML,63.1,high
2,13105598,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.3,339516,3.5-4 ML,63.1,high
3,13105594,lipstick,Lakme 9to5 Powerplay Priming Matte Lipstick Wi...,Lakme,650.0,240,410,4.3,339516,3.5-4 ML,63.1,high
4,30593165,lipstick,Pilgrim Matte Bullet Intense Colour Transferpr...,Pilgrim,595.0,357,238,4.3,19624,4-5 ML,40.0,medium

In [34]:
# connecting to MYSQL

from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost:3306/myntra_analysis"
)

print("Connection created")

Connection created

In [35]:
df.to_sql(
    name='cosmetics',
    con=engine,
    if_exists='replace',
    index=False
)

18907

In [35]:
%pip install cryptography

Collecting cryptography
  Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl.metadata (4.4 kB)
Requirement already satisfied: cffi>=2.0.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)
Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.8 MB 374.9 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.8 MB 374.9 kB/s eta 0:00:09
   -------- ------------------------------- 0.8/3.8 MB 520.1 kB/s eta 0:00:06
   -------- ------------------------------- 0.8/3.8 MB 520.1 kB/s eta 0:00:06
   -------- ------------------------------- 0.8/3.8 MB 520.1 kB/s eta 0:00:06
   ---------- ----------------------------- 1.0/3.8 MB 457.1 kB/s eta 0:00:07
   ---------- ----------------------------- 1.0/3.8 MB 457.1 kB/s eta 0:00:07
   ------------- -------------------------- 1.3/3.8 MB 518.5 kB/s eta 0:00:05
   ------------- -------------------------- 1.3/3.8 MB 518.5 kB/s eta 0:00:05
   ---------------- ----------------------- 1.6/3.8 MB 539.7 kB/s eta 0:00:05
   ------------------- -------------------- 1.8/3.8 MB 575.5 kB/s eta 0:00:04
   ------------------- -------------------- 1.8/3.8 MB 575.5 kB/s eta 0:00:04
   --------------------- ------------------ 2.1/3.8 MB 603.8 kB/s eta 0:00:03
   --------------------- ------------------ 2.1/3.8 MB 603.8 kB/s eta 0:00:03
   ------------------------ --------------- 2.4/3.8 MB 619.6 kB/s eta 0:00:03
   --------------------------- ------------ 2.6/3.8 MB 644.1 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 678.6 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 678.6 kB/s eta 0:00:02
   -------------------------------- ------- 3.1/3.8 MB 675.0 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.8 MB 699.6 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 711.8 kB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 708.0 kB/s  0:00:05
Installing collected packages: cryptography
Successfully installed cryptography-50.0.2
Note: you may need to restart the kernel to use updated packages.